name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Nuxt app
      run: npm run build

    - name: Deploy to Azure
      uses: azure/static-webapps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        app_location: '/'
        api_location: '.output/server'
        output_location: '.output/public'
